# Generated by Django 3.1.3 on 2020-12-01 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201202_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
