# Generated by Django 3.1.3 on 2021-07-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uiux_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='video_test',
            field=models.BooleanField(default=False),
        ),
    ]
