# Generated by Django 3.1.3 on 2020-12-01 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_editorial_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='design_test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='editorial_test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='management_test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=1234567890, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='technical_test_passed',
            field=models.BooleanField(default=False),
        ),
    ]
