# Generated by Django 3.1.3 on 2020-12-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201205_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_no',
            field=models.CharField(default='19BIT0000', max_length=10),
        ),
    ]
